language: python
python:
    # - "3.6"
    - "3.7"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: "make"

script: 
  - make test
  
before_install:
  - "pip install -U pip"
  - "python setup.py install"

after_success:
  - "coveralls"